const adjectives = [
  '3d printed',
  'adhesive',
  'anthropomorphistic',
  'artsy',
  'automated',
  'autonomous',
  'bio wearable',
  'biodegradable',
  'blinking',
  'charitable',
  'cleaning',
  'connected',
  'cooking',
  'crypto',
  'downloading',
  'energy',
  'green/eco',
  'harvesting',
  'hydroponic',
  'inductive',
  'interactive',
  'lockpicking',
  'magnetic',
  'mechanical',
  'medical',
  'multitouch',
  'musical',
  'nuclear',
  'online',
  'optical',
  'painting',
  'portable',
  'privacy',
  'radio-active',
  'repairing',
  'responsive',
  'retrotechtacular',
  'secure',
  'self healing',
  'self-aware',
  'self-balancing',
  'selfdestroying',
  'simplified',
  'solar',
  'sustainable',
  'teardown',
  'thermal',
  'tiny',
  'tunable',
  'tweeting',
  'ultra-sonic',
  'universal',
  'voice controlled',
  'vulnerable',
  'water proof',
  'water resistant',
  'weaponized',
  'wearable',
  'wireless',
  'chemical',
  'open source'
]

const nouns = [
  '3d Printer',
  'Accelerometer',
  'Android',
  'Arduino',
  'ARM processor',
  'audio device',
  'automation',
  'Beer',
  'Big Data',
  'car',
  'carbon',
  'cellphone',
  'clock',
  'cnc',
  'coffee',
  'computer',
  'cooking',
  'Crowd Funding',
  'data mining',
  'digital camera',
  'door bell',
  'download',
  'dream',
  'drink',
  'drone',
  'eBook reader',
  'energy',
  'Engine',
  'entertainment',
  'ePaper',
  'exoskeleton',
  'flashlight',
  'FPGA',
  'Game console',
  'garden',
  'GPS',
  'Hackerspace',
  'ham radio',
  'handheld',
  'home',
  'induction',
  'injection',
  'instrument',
  'internet',
  'IoT',
  'key fob',
  'laptop',
  'laser',
  'LED cube',
  'led',
  'lifehacks',
  'light switch',
  'linux',
  'lockpicking',
  'machine learning',
  'magic smoke',
  'Microcontroller',
  'MIDI',
  'mobile App',
  'monitor',
  'mp3 player',
  'Network',
  'Nixie Tube',
  'painting',
  'PDA',
  'peripheral',
  'pet',
  'phone',
  'podcast',
  'printer',
  'projector',
  'prosthetic',
  'radio',
  'Raspberry Pi',
  'rfid',
  'RGB',
  'robot',
  'search engine',
  'security',
  'sensor array',
  'servo',
  'sleep',
  'slider',
  'smartwatch',
  'soldering',
  'tablet',
  'tool',
  'toy',
  'transportation',
  'USB Dongle',
  'video device',
  'Virtual Reality',
  'weapon',
  'wheatherstation',
  'wheelchair',
  'workbench',
  'BTLE',
  'cloud',
  'ESP8266',
  'fusion',
  'glue gun',
  'graphene',
  'space ship',
  'Supercapacitor'
]

function getRandomInt (size) {
  return Math.floor(Math.random() * size)
}

export default () => {
  const random1 = getRandomInt(adjectives.length)
  const random2 = getRandomInt(nouns.length)
  let text = `${adjectives[random1]} ${nouns[random2]}`
  if (Math.floor(Math.random() + 0.5)) {
    const random3 = getRandomInt(nouns.length)
    text += ` ${nouns[random3]}`
  }
  return text
}
